#!/bin/bash
# minimal open script for fuf

runquiet() { "$@" &> /dev/null; } # run without output on terminal

# filetype handlers
case $(file --mime-type -Lb "$1") in
	video/* | audio/*)
		runquiet mpv -no-terminal --force-window "$1" && exit;;
	*/x-xcf)
		runquiet gimp "$1" && exit;;
	image/*)
		runquiet mpv --loop-file=inf --no-terminal "$1" && exit;;
	*/pdf)
		runquiet zathura "$1" && exit;;
esac

# special case for 'last Q' mpv playlist markers
[[ "$1" == "!lastQ" ]] && mpv --no-terminal "$(cat '!lastQ')" && exit

# open everything else in editor
$EDITOR "$1"
